from environs import Env

env = Env()
env.read_env()  # Read the .env file, if it exists

# ACCESS THE ENVIRONMENT VARIABLES
# SECRET KEY
SECRET_KEY = env('SECRET_KEY')

# DATABASE VARIABLES
MYSQL_HOST = env('MYSQL_HOST')
MYSQL_PORT = env('MYSQL_PORT')
MYSQL_USER = env('MYSQL_USER')
MYSQL_PASSWORD = env('MYSQL_PASSWORD')
MYSQL_DB = env('MYSQL_DB')
MYSQL_DATABASE_URI = env('MYSQL_DATABASE_URI')

# MAIL VARIABLES
MAIL_SERVER = env('MAIL_SERVER')
MAIL_PORT = env('MAIL_PORT')
MAIL_PASSWORD = env('MAIL_PASSWORD')
MAIL_USE_TLS = env('MAIL_USE_TLS')
MAIL_USE_SSL = env('MAIL_USE_SSL')
MAIL_USERNAME = "support@mintverse.art"
MAIL_DEFAULT_SENDER = "support@mintverse.art"  # Default sender address


ADMIN_NAME = env("ADMIN_NAME")
ADMIN_EMAIL = env("ADMIN_EMAIL")
ADMIN_PASSWORD = env("ADMIN_PASSWORD")
